[versions]
agp = "8.7.1"
android-compileSdk = "35"
android-minSdk = "26"
android-targetSdk = "35"
androidx-activityCompose = "1.9.3"
storytale = "0.0.2+dev6"

compose-plugin = "1.8.0-alpha02"
compose-navigation = "2.8.0-alpha12"
kotlinx-serialization-json = "1.7.3"
kotlin = "2.1.0"
kotlin-poet = "1.18.1"
build-time-config = "2.3.0"
code-highlights = "0.9.3"
dokka = "1.9.10"
kotlinx-html = "0.7.3"
junit = "5.10.1"
jsoup = "1.16.1"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
compose-gradle-plugin = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "compose-plugin" }
kotlin-compiler-embeddable = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlin" }
kotlin-poet = { module = "com.squareup:kotlinpoet", version.ref = "kotlin-poet" }
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "compose-navigation" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
compose-highlights = { module = "dev.snipme:highlights", version.ref = "code-highlights" }
dokka-core = { module = "org.jetbrains.dokka:dokka-core", version.ref = "dokka" }
dokka-base = { module = "org.jetbrains.dokka:dokka-base", version.ref = "dokka" }
dokka-test-api = { module = "org.jetbrains.dokka:dokka-test-api", version.ref = "dokka" }
dokka-base-test-utils = { module = "org.jetbrains.dokka:dokka-base-test-utils", version.ref = "dokka" }
kotlinx-html = { module = "org.jetbrains.kotlinx:kotlinx-html-jvm", version.ref = "kotlinx-html" }
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
buildTimeConfig = { id = "dev.limebeck.build-time-config", version.ref = "build-time-config" }
storytale = { id = "org.jetbrains.compose.storytale", version.ref = "storytale" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
