name: Smoke build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  build:
    name: Publish to MavenLocal and Build Examples
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Test Dokka Plugin
        run: ./gradlew :modules:dokka-plugin:test

      - name: Publish to Maven Local
        run: ./gradlew publishToMavenLocal

      - name: Build gallery-demo
        run: |
            ./gradlew :gallery-demo:wasmJsBrowserDevelopmentExecutableDistribution :gallery-demo:packageReleaseUberJarForCurrentOS

      - name: Build Stories for Wasm target
        run: |
          cd examples
          ../gradlew wasmJsBrowserStoriesProductionExecutableDistribution

      - name: Build Stories for Desktop target
        run: |
          cd examples
          ../gradlew desktopStorytaleGenerate
